import 'dart:async';
import 'package:flutter/cupertino.dart';

StreamController<String> displayStream = StreamController.broadcast();
StreamController<String> displaySizeStream = StreamController.broadcast();
StreamController<int> baseNCardStream = StreamController.broadcast();
StreamController<bool> activatedStream = StreamController.broadcast();
StreamController<IconData> operatorStream = StreamController.broadcast();
StreamController<bool> willOperateStream = StreamController.broadcast();
StreamController<bool> chainOperateStream = StreamController.broadcast();
StreamController<int> binaryStream = StreamController.broadcast();
String displayValue = '0';
double displaySize = 60;
bool onHex = false;
bool onDec = true;
bool onOct = false;
bool onBin = false;
List<String> notDec = ['A', 'B', 'C', 'D', 'E', 'F'];
List<String> notOct = ['A', 'B', 'C', 'D', 'E', 'F', '8', '9'];
List<String> notBin = ['A', 'B', 'C', 'D', 'E', 'F', '2', '3', '4', '5', '6', '7', '8', '9'];
int firstValue = 0;
int secondValue = 0;
int currentOperator = 0;
String displayHex = '0';
String displayDec = '0';
String displayOct = '0';
String displayBin = '0000';
bool chainOperate = false;
bool onOnes = false;
bool onTwos = false;
bool onChangeSign = false;
bool isNegative = false;
bool moduloNegative = false;